# Set 1
baseURL=https://goorulogin-portal-stage.azurewebsites.net/
baseURLRegister=https://goorulogin-portal-stage.azurewebsites.net/signup
baseURLAdmin=https://goorulogin-portal-stage.azurewebsites.net/admin
email=poonam.kumari@yopmail.com
password=Test@1234
#Post
postTitle=This is my first post
postDescription=This is my first post about Gooru Application
#Gooru Profile Complete
Generation=Youth
GooruTitle=Software Engineer
date=06/11/2026
hour=11
minute=35
#Set 2
user2=ss
pass2=Test@125
#set 3
gemail=gooruaitest@gmail.com
gpassword=Gmail@4321
#Registration
tempemailurl=https://yopmail.com/
FirstName=kon
LastName=tifi
Remail=kontifi@yopmail.com
Rpassword=Test@1234
RCpassword=Test@1234
phone=2925454860
dob=10/10/1989
LearnerBio=I am tech person. I want to enroll into IamGuru Application to explore new things.
PlatformName=Facebook
PlatformUrl=https://www.facebook.com
Quality=Leadership
#ResetPassword
usernewpassword=Test@12345
userconfirmpassword=Test@12345
Chatbot question=Test
#Course Management
CourseName=Core Java
CourseDescription=Core Java is a programming language that is used to develop applications for the web, mobile, and desktop.

